# This is a basic workflow to help you get started with Actions

name: Convert PDF to Markdown

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    paths:
    - '**.md'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  convert_md:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
    # We must checkout the latest version of the code to get a copy of all .md files
    - name: Checkout Code
      uses: actions/checkout@v2.0.0
      env:
        DEBIAN_FRONTEND: noninteractive
      with:
        fetch-depth: 1
    - name: Create .mds
      uses: baky0905/docx-to-md@v0.1.2
      env: 
        MD_DIR: './mds'
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v1.6.1
      env:
        DEBIAN_FRONTEND: noninteractive
        # The token is built in to actions. No config required.
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Add .md files.
        PULL_REQUEST_TITLE: Add .md files.
        PULL_REQUEST_BRANCH: md-add  
